### ISSUE TITLE
Breakpoints in .asm file

### ISSUE THREAD

**Issue by joeparis** [newtonsart/vscode-assembly#2]
First, let me say thank you for posting your `tasks.json` and `launch.json` files, they have been extremely helpful to me as I am setting up VS Code to do remote ASM development in WSL! I teach a computer architecture and assembly language course and my students these days are very much used to using VS Code. 

Sorry to submit an issue for this, but I am pulling my hair out over this.... how did you set a breakpoint in the .asm file as you show in your README? I've installed GNU Debug and am using your files as a guide to setting up my tasks and debugging configs but I cannot get VS Code to put a breakpoint in an assembler file. Does the ability come from a language provider you have installed? Am I missing an option in my settings? Or is it a deeper, darker magick? 😉 

Any guidance would be appreciated!!

**Comment by newtonsart** [comment]
Hello, thank you very much for reviewing this. I made it while I was learning assembly, so I hope this is helpful for everyone interested in learning assembly.

Don't worry about submitting an issue. You need to go to VS->Settings->Debug and change "debug.allowBreakpointsEverywhere" to true. And then you'll be able to set breakpoints in the code.

I hope this will help you :)
