### ISSUE TITLE
[Unable to see Registers View]

### ISSUE THREAD

**Issue by pearldarkk** [newtonsart/vscode-assembly#6]
Hi, 
Thanks so much for your useful sharing. I have followed exactly your instruction and used your configuration files. I can debug now with my nasm programs. Unfortunately, while debugging, I can't see my registers. When I clicked on "registers" it shows nothing. Here is my variables view when debugging:  

![registers](https://user-images.githubusercontent.com/58837237/150639119-d0b237fd-017e-4533-a867-3a96de5e5bc1.png)  

I'd be grateful if you can help me out!

Thanks again.

[Edit] I have tried with x86 nasm and it still show registers. Seems like problem only appears with x64.... 
By the way, is there anyway I could see memory or to see my variables (like num1 or num2 in the picture above)?

**Comment by pearldarkk** [comment]
In addition, I built the program successfully. I executed it fine, too.

**Comment by newtonsart** [comment]
So this is problem of the [GDB debug extension](https://marketplace.visualstudio.com/items?itemName=DamianKoper.gdb-debug&ssr=false#qna), this is a big problem because it is no longer under development. the only way of fixing this is with an alternative to this extension.

**Comment by Fares-Steen** [comment]
I had the same problem while trying to debug 32 bit in a 64 system.

You need to update the tasks for GAS command  to be like this:
"command": "rawfilename=${fileDirname}/${fileBasenameNoExtension}; as --32 --gstabs+ ${file} -o $rawfilename.o; ld -m elf_i386 $rawfilename.o -o $rawfilename",

**Comment by newtonsart** [comment]
issue should be fixed now

**Comment by paviln** [comment]
Hi. 

What command should be used to debug GAS 64 bit? Since i am also not getting registers showed, with the following:           "command": "rawfilename=${fileDirname}/${fileBasenameNoExtension}; as --gstabs ${file} -o $rawfilename.o; ld $rawfilename.o -o $rawfilename",
